version: '3'
services:
  api_svc:
    build: 
      context: ../
      dockerfile: dev/Dockerfile
    container_name: my_api
    depends_on:
      - redis_svc
      - mongo_svc
    env_file:
      - .env
    image: my_api_img
    networks:
      - my_network
    ports:
      - "80:8000"
    volumes:
      - '../app:/usr/src/host_app'
    working_dir: /usr/src/host_app
  mongo_svc:
    container_name: my_mongo
    image: mongo
    networks: 
      - my_network
    ports:
      - "27017:27017"
  redis_svc: 
    container_name: my_redis
    image: redis
    networks:        
      - my_network
    ports:
      - "6379:6379"
networks:
  my_network:

