version: '3'
services:
  api_svc:
    build: 
      context: ../
      dockerfile: dev/Dockerfile
    command: gunicorn main:create_app()
    container_name: my_api
    depends_on:
      - redis_svc
    env_file:
      - env
    image: my_api_img
    networks:
      - my_network
  redis_svc: 
    container_name: my_redis
    image: redis
    networks:        
      - my_network
networks:
  my_network:

