version: '3'
services:
  api_svc:
    build: 
      context: ../
      dockerfile: dev/Dockerfile
    container_name: api-dev
    depends_on:
      - redis_svc
      - mongo_svc
    env_file:
      - .env
    image: api-img
    networks:
      - api-network
    ports:
      - "80:8000"
    volumes:
      - '../app:/usr/src/host_app'
    working_dir: /usr/src/host_app
  mongo_svc:
    container_name: api-mongo
    image: mongo
    networks: 
      - api-network
    ports:
      - "27017:27017"
  redis_svc: 
    container_name: api-redis
    image: redis
    networks:        
      - api-network
    ports:
      - "6379:6379"
networks:
  api-network:
    name: api-network

